version: "3.3"
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3355:3355"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=db
        